//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Project/Configs/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Project.Input
{
    public partial class @GameInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Level Menu"",
            ""id"": ""ea6a1f8f-6d14-42e0-a3b4-006ffb3b1368"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a11f594e-6541-4fad-85a2-f0c8c19935ce"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""35a08a43-d783-4c2e-976b-b218d289e3d2"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Level Menu
            m_LevelMenu = asset.FindActionMap("Level Menu", throwIfNotFound: true);
            m_LevelMenu_Move = m_LevelMenu.FindAction("Move", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Level Menu
        private readonly InputActionMap m_LevelMenu;
        private ILevelMenuActions m_LevelMenuActionsCallbackInterface;
        private readonly InputAction m_LevelMenu_Move;
        public struct LevelMenuActions
        {
            private @GameInput m_Wrapper;
            public LevelMenuActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_LevelMenu_Move;
            public InputActionMap Get() { return m_Wrapper.m_LevelMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LevelMenuActions set) { return set.Get(); }
            public void SetCallbacks(ILevelMenuActions instance)
            {
                if (m_Wrapper.m_LevelMenuActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_LevelMenuActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_LevelMenuActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_LevelMenuActionsCallbackInterface.OnMove;
                }
                m_Wrapper.m_LevelMenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                }
            }
        }
        public LevelMenuActions @LevelMenu => new LevelMenuActions(this);
        public interface ILevelMenuActions
        {
            void OnMove(InputAction.CallbackContext context);
        }
    }
}
